### ISSUE TITLE
better syntax for variables

### ISSUE THREAD

**Issue by xcoderzach** [Amicus/end-dash#9] opened 2013-08-14 22:09 UTC
variables need a better syntax.

``` html
<div class="user-">
  user's name is #{name}.
</div>
```

would be sick.

**Comment by xcoderzach** [comment] 2013-08-21 14:14
NOTE TO SELF:
https://developer.mozilla.org/en-US/docs/Web/API/Text.splitText makes this super simple!  HAH HA!

**Comment by yaymukund** [comment] 2013-12-03 15:55
I think this is a duplicate of #73 ?

**Closed as completed by yaymukund** 2013-12-03 15:55 UTC
